### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by meetdilip**
I am new to Github. Hopefully, this new icon will be added to the Calibre-icon-theme. Kindly let me know if any changes are required.

### CODE REVIEW

**Comment by SmartFinn** [comment]
@meetdilip Thanks, but

1. This is not a Papirus icon.
2. The icons of the theme must be in an SVG format and placed in https://github.com/PapirusDevelopmentTeam/papirus-calibre-theme/tree/master/imgsrc directory.

Rejected.

**Comment by varlesh** [comment]
@meetdilip we approve participation, but i think need develop this theme with SVG's, because it comphortable for fixes and more suitable for future development. See other themes, mostly use SVG sources and converted to PNG

**Comment by meetdilip** [comment]
@SmartFinn What do you expect in a Papirus icon ? I mean, how different do you want it to be from the one I just tried ?

@varlesh Sure. Thanks. I will follow the same. :)

**Comment by SmartFinn** [comment]
@meetdilip find an icon  in [papirus-icon-theme/Papirus/48x48](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/tree/master/Papirus/48x48) that looks similar to an icon from default [Calibre theme](https://github.com/PapirusDevelopmentTeam/papirus-calibre-theme/tree/master/calibre/images). Then just paste the icon to `_TEMPLATE.SVG`, increase it twice, and save with correct filename (add_book.svg in this case)

screenshot from 2017-09-24 07-57-37

**Comment by varlesh** [comment]
Also not forgot about pixel align. Enable grid (shift+3).

**Comment by SmartFinn** [comment]
I'm not sure that using this template correctly.

@azadaquib could you give an example how to optimize exist Papirus icon to Calibre theme?

**Comment by meetdilip** [comment]
@varlesh What is pixel align ? I am new to professional templates

@SmartFinn How to use those icon shadows ? I am not sure how to make them the easy way

Do you guys like this one ? Just made it

add_book 1x

or this ?

add_book 2x

**Comment by SmartFinn** [comment]
@meetdilip you don't need to create a new icon. Most icons already exists in [papirus-icon-theme/Papirus/48x48](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/tree/master/Papirus/48x48).

**Comment by varlesh** [comment]
@meetdilip all items (circle, square, lines, object ) are pixel-aligned and have a round value of size.
image

**Comment by meetdilip** [comment]
Which one should I use ? Inkscape SVG or Plain SVG ?

@varlesh , is pixel align just a standard practice ? Or, any benefit from it ?

**Comment by SmartFinn** [comment]
@meetdilip wait for @azadaquib response.

**Comment by varlesh** [comment]
> Which one should I use ? Inkscape SVG or Plain SVG ?

For main Papirus icon theme we save file as Inkscape SVG, but then clear code with svgo and config. But for themes (smplayer, amule and etc...) it's doesn't matter, because icon converted to PNG anyway.

> @varlesh , is pixel align just a standard practice ? Or, any benefit from it ?

It's Papirus HIG - all icons use pixel align. See https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/tree/master/tools/work

**Comment by meetdilip** [comment]
> It's Papirus HIG

What is HIG ?

@SmartFinn 

I have corrected the add_book.svg. Can I make a PR ?

**Comment by varlesh** [comment]
Human Interface Guidelines

**Comment by meetdilip** [comment]
@SmartFinn , Busy ?

**Pull request closed without merging**
